sudo: required
language: bash
services:
  - docker

env:
  global:
    - IMG=biggis/kafka:0.10.1.1

install:
  #login to dockerhub
  - docker login --username=$DOCKER_HUB_USERNAME --password=$DOCKER_HUB_PASSWORD

script:
  #build the images
  - docker build --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` --build-arg VCS_REF=`git rev-parse --short HEAD` -t $IMG .

after_success:
  - echo "build successful"
  #push the image to dockerhub
  - docker push $IMG
