version: '2.1'
services:

  zookeeper:
    image: biggis/zookeeper:3.4.9
    hostname: zookeeper
    ports:
      - "2181:2181"
    environment:
      USER_ID: ${USER_ID-1000}
      USER_NAME: zookeeper
    # volumes:
    #   - zookeeper-data:/tmp/zookeeper/data

  kafka:
    #image: biggis/kafka:0.10.1.1
    image: kafka
    hostname: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: ${DOCKER_HOST_IP-localhost}
      KAFKA_NUM_PARTITIONS: 1
      KAFKA_MESSAGE_MAX_BYTES: 1000000
      ZOOKEEPER_CONNECTION_STRING: zookeeper
      USER_ID: ${USER_ID-1000}
      USER_NAME: kafka
    # volumes:
    #   - kafka-data:/tmp/kafka/data

# volumes:
  # zookeeper-data:
  # kafka-data:
