version: '2'
services:

  zookeeper:
    image: biggis/zookeeper:3.4.9
    hostname: zookeeper
    ports:
      - "2181:2181"
    labels:
      io.rancher.container.pull_image: 'always'
    environment:
      USER_ID: 1000
      USER_NAME: zookeeper
    volumes:
      - zookeeper-data:/tmp/zookeeper/data
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

  kafka:
    image: biggis/kafka:0.10.1.1
    hostname: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    labels:
      io.rancher.container.pull_image: 'always'
      io.rancher.scheduler.affinity:host_label: kafka=true
    environment:
      KAFKA_ADVERTISED_HOST_NAME: node1.biggis.project.de
      KAFKA_NUM_PARTITIONS: 1
      KAFKA_MESSAGE_MAX_BYTES: 1000000
      ZOOKEEPER_CONNECTION_STRING: zookeeper
      USER_ID: 1000
      USER_NAME: kafka
    volumes:
      - kafka-data:/tmp/kafka/data
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

volumes:
  zookeeper-data:
    driver: rancher-nfs
    external: true
  kafka-data:
    driver: rancher-nfs
    external: true
